### ISSUE TITLE
Capturing signing algorithm

### ISSUE THREAD

**Issue by Gozala** [ucan-wg/ucan-ipld#4]
My attempt to implement support for arbitrary DIDs in dag-ucan made me realize that there is a problem in regards to capturing signing algorithm (a.k.a signature types). There is some relevant discussion in this thread https://github.com/ucan-wg/ucan-ipld/pull/1/files#r968831768

More concretely currently dag-ucan supported only `did:key:`s. There also was no reason for [`alg`](https://github.com/ucan-wg/spec#31-header) field because `did:key:`s have a multiformat tag for `public-key-type` as per spec:

```
 did-key-format := did:key:MULTIBASE(base58-btc, MULTICODEC(public-key-type, raw-public-key-bytes)) 
```

This is also what was used to derive `alg` header when when formatting IPLD ucan into JWT. 

Now if we want to support arbitrary did's things are trickier because there is no clear way to derive signature algorithm from say `did:dns:danubetech.com`.

**Comment by Gozala** [comment]
Straightforward solution could be to add `alg` field into an IPLD schema and call it a day. I'm not super fond of this approach because if say `alg` and `public-key-type` tag mismatch we have a invalid UCAN.

I think better alternative would be to use tag signatures with `public-key-type` multiformat tag which would give us "multisignature" (not as in multisig 😭) kind of like a [multihash](https://github.com/multiformats/multihash) but for signatures.

For one it would take up less space, but it also would make a more plug-able interface IMO, specifically:

```ts
interface Principal<Method extends string = string> {
  // formats principal into DID string
  did(): `did:${Method}:${string}`
  // encodes principal into UCAN ipld `iss` or `aud` field
  encode(): Uint8Array

  // verifies that payload was signed by this principal
  verify(payload:Uint8Array, signature:MultiSignature): Promise<boolean>
}

interface SigningPrincipal<Method extends string = string> extends Principal<Method> {
  sign(payload: Uint8Array): Promise<MultiSignature>
}

interface MultiSignature<Code extends number = number> extends Uint8Array, Phantom<{ publicKeyType: Code }> {} 
```

That way implementation:

1. Can take `SigningPrincipal` for the `iss` and `Principal` for the `aud` when issuing UCANs and
    - Encode principal to bytes
    - Sign UCAN with principal & possibly do some IO when it's something like `did:dns:...`.
    - Derive JWT `alg` from the produced `MultiSignature`
2. IPLD codec could format UCAN into JWT by deriving `JWT` alg from the `MultiSignature`.
3. Fold signature algorithm validation problem of `verify` method of the `Principal`.

**Comment by expede** [comment]
> I think better alternative would be to use tag signatures with public-key-type multiformat tag which would give us "multisignature" (not as in multisig 😭) kind of like a [multihash](https://github.com/multiformats/multihash) but for signatures.

As we're discovering adding MetaMask support, it's unfortunately more than the correlated public key. `secp256r1` can sign as _both_ [ECDSA](https://en.wikipedia.org/wiki/Elliptic_Curve_Digital_Signature_Algorithm) and the [EIP-191](https://eips.ethereum.org/EIPS/eip-191) Ethereum signature format (AFAIK EIP-191 is the only way that MetaMask will sign, which is annoying). EIP-191 and EIP-1271 are requirements for [SIWE](https://eips.ethereum.org/EIPS/eip-4361), which gets us out-of-the-box support for everyone with a blockchain wallet.

I believe that [CACAO uses a struct](https://github.com/ceramicnetwork/cacao/blob/d18d3f40bddd07d7a4ee5959f003c3416c9e1442/src/cacao.ts#L37-L40), but I'm unsure if they have a tighter representation on serialization.

```ts
export type Signature = {
  t: 'eip191' | 'eip1271' | 'solana:ed25519'
  s: string
}
```

@oed & @ukstv, do you have any insights on the design space?

I personally like the idea of a `multisignature` type, where the tag for "standard" signatures is the same as the public key type, with special reserved ones for EIP-191 etc. I'm also open to an `alg` parameter in the UCAN-IPLD representation, though.

**Comment by expede** [comment]
> I think better alternative would be to use tag signatures with public-key-type multiformat tag which would give us "multisignature" (not as in multisig 😭) kind of like a [multihash](https://github.com/multiformats/multihash) but for signatures.

> I personally like the idea of a multisignature type, where the tag for "standard" signatures is the same as the public key type, with special reserved ones for EIP-191 etc

Which would could be as simple as...

## 1. Flat "Just Use Multicodec" Namespace

Basically follow the pattern in multicodec, and add a bunch of special signature types for various ECDSA signatures (NIST curves, secp256r1, etc), Ed25519, RSA, and so on.

```
rsa-sig-format := MULTIBASE(base, MULTICODEC(rsa-sig-tag, raw-rsa-sig))
secp256r1-sig-format := MULTIBASE(base, MULTICODEC(secp256r1-sig-tag, raw-ecdsa-sig))
eip-191-sig-format := MULTIBASE(base, MULTICODEC(eip-191-sig-tag, raw-eip-191-sig))
```

The major downside is that the multicodec table is really hard to update.

## 2. Special Signature Tag with Nesting

Have a "this is a signature" tag, use the equivalent public key tag as a modifier, and leave space for arbitrary signature formats.

```
sig-format := MULTIBASE(base, MULTICODEC(sig-tag, sig-type, raw-siganture-bytes))
```

For argument sake, let's say that the "this is a signature" tag is `0xc0ffee`.

| Public Key | Signature Type              | Byte Sequence                         |
| ---------- | --------------------------- | ------------------------------------- |
| Ed25519    | Ed25519                     | `0xc0ffee + 0x00ed + rawEdSig`        |
| RSA        | RSA-DER-ASN.1 PKCS-1 (seriously, there's several) | `0xc0ffee + 0x1205 + rawRsaSig`       |
| secp256k1 (ETH & BTC) | :sparkles: ECDSA :sparkles: | `0xc0ffee + 0x0039 + rawSecp256k1Sig` |
| secp256k1             | :sparkles: EIP-191 :sparkles: | `0xc0ffee + 0xe191 + rawEthSig`       |

I think that this is more elegant than option 1, and lets us define whatever we want inside the namespace.

## 3. Algorithm Field

Use the JWT `alg` field, which uses more bytes. I don't know if it gets us much over option 2 other than the fact that we can put whatever string in there easily.

# A Note on Capability

Of course, people should use common signature types whenever possible, otherwise the chance that someone can't validate their signature goes way way up. The same goes for DID types. If they bake the signature down to `did:key`, it becomes self-verifying and works offline. If they use (e.g.) `did:ion` or `did:dns`, they gain the ability to rotate keys, but lose the ability to work offline. If I create `did:expede`, then I really can't expect anyone else to be able to validate my DID 🤷‍♀️

**Comment by oed** [comment]
Would be great to see a multicodec for signature types, although it might become quite burdensome to maintain?
I could also see us adopting it in CACAO.

fyi, BTC and Eth uses `secp256k1` not `-r1`

**Comment by expede** [comment]
> BTC and Eth uses secp256k1 not -r1

Ah lol indeed. So many curves to keep track of 😅

**Comment by expede** [comment]
@Gozala while it's a bit of yak shaving, my gut keeps telling me that a `multisiganture` would be useful. My proposal looks roughly as above.

1. Get a `signature` prefix into multicodec
1. Break out `multisignature` spec
    * Lets us be more agile than `multicodec`
    * Don't pollute the global namespace
    * Format as above
1. Use that in UCAN IPLD

Whichever strategy we pick, ideally we move on it relatively soon so that we don't have to version `ucan-ipld`.

Thoughts?

**Comment by Gozala** [comment]
As far as I understand only benefit of no 2 is the fact that we do not have to deal with registering multicodec codes for each signature type/algorithm. I have couple of sentiments on that:

1. I am personally not sure we really need to register each signature type with multicodec table, we could simply define our own code table in the spec and call it a day.
2. Currently [multicodec table](https://github.com/multiformats/multicodec/blob/master/table.csv#L39) has a code for each hashing algorithm and that precedent seems to suggest that registering code for every `multisignature` is a way to go.
3. On the other hand having additional tag per class may have made multicodec table shorter and required less of a consensus building around it.

With all the above I'm inclined to just open an issue in https://github.com/multiformats/multicodec/ repo offering both options and see what advice we get. Personally I would go with flat list (unless we're highly encouraged to to go with no 2) and not block on code registrations but replicate additions async.


I think it also may be worth considering option 3, which would be something along the lines of what CACAO is doing:

```ipldsch
type Signature struct {
  alg: Int
  out: Bytes
}

type UCAN struct {
  s: Signature
  -- etc
}
```

On related note I have created a proposal to allow misrepresenting such structs in multiformat encoding see https://github.com/ipld/ipld/issues/241

There is also option 4 

@warpfork pointed out to me that we could use [byteprefix represenation of unions](https://ipld.io/docs/schemas/features/representation-strategies/#union-bytesprefix-representation) for the signature types e.g. it could look like:

```ipldsch
type Signature union {
  | Ed25519Signature "0xed"
  | RSASignature "0x1205"
  | ECDSASignature "0x0039"
  | EIP191Signature "0xe191"
} representation bytesprefix

type Ed25519Signature = bytes
type RSASignature = bytes
type ECDSASignature = bytes
type EIP191Signature = bytes
```

**Comment by Gozala** [comment]
I think I'd like to go with Option 4 and propose registering our signature codes for multicodec table. If we're highly encouraged to go with nested tagging option, we can add another byteprefix via:

```ipldsch
type MultiSignature union {
  | Signature "0xc0ffee"
}
```

**Comment by Gozala** [comment]
Also I don't think we can use "multisignature" term it's just going to be too confusing given that multisig means something else. I think we could either call it `varsig` or `autosig` or some other thing instead.

**Comment by Gozala** [comment]
I have realized we have additional complication when it comes to signatures types and arbitrary DIDs, that is if I get a JWT encoded UCAN with some exotic signing algorithm e.g. `EX256` there will be no way of turning it into IPLD UCAN because who knows what multiformat code does that correspond to ?

Reverse is the problem as well, if I came across the IPLD UCAN with unknown code e.g. `0x0e256` there will be no way to format it as JWT as it is unclear what `header.alg` would that correspond to 😭

I don't know, maybe this is not a big deal in practice, but it does really bother me and I wonder if going back to dumb structure like below is more practical way forward:

```ipldsch
type Signature struct {
  alg: String
  out: Bytes
}
```

That way we could just copy `alg` between IPLD and JWT representations as is

**Comment by expede** [comment]
@Gozala oh yeah that's a good point. In essence, I still like your idea of keeping on the happy path whenever possible, and in fact I think people will be incentivized to do this for interoperability.

If you get an `alg: EX256` UCAN, one of two things could happen:

# 1. Treat It as Raw

Fail the parser, and treat it as a non-canonicalized UCAN (we already need to handle this case). This doesn't handle anything that's not registered 

I like this one because it's dead simple, and really makes clear that they're going off the happy path.

# 2. Use an Escape Hatch

Include the `alg` header in the...

```ts
type NonStandardSiganture union {
  -- Example: EIP1271 "0xd01271"
} representation bytesprefix
```

...and format something like `0xd000 + "EX256".toHex() + delimiter + sig`.

I like this because it gives people room to innovate while they wait for the spec to update without having to fork all of their tools.

# 3. Separate `alg` header

As you suggested:

```ts
type Signature struct {
  alg: String
  out: Bytes
}
```

This is equivalent to (2), but less directed towards known/supported signature schemes. I'm also fine with this one, but I like that the others push people to use the "blessed" signatures.

---

Thoughts?

**Comment by Gozala** [comment]
I do like option 2 with slight modification how about we represent it as following multiformat, which is just like other signatures except we prepend UTF8 encoded name. We don't need delimiter because we encode signature size anyway

```
<varint 0xd000><varint sig_size><sig_bytes><alg_in_utf8>
```

**Comment by expede** [comment]
Sounds good to me! I'll add that to the PR 👍
